// <auto-generated />
using System;
using BL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BL.Migrations
{
    [DbContext(typeof(AlMohamyDbContext))]
    [Migration("20230417212335_r5")]
    partial class r5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BL.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsultingNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaysOfWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EvaluationNoOfStatrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluationNumerical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoursOfWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MainConsultingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainConsultingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsOfExperience")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Domains.TbAboutApp", b =>
                {
                    b.Property<Guid?>("AboutAppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AboutAppDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("AboutAppForWhom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AboutAppTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("AboutAppId");

                    b.ToTable("TbAboutApp");
                });

            modelBuilder.Entity("Domains.TbActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentState")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Id");

                    b.ToTable("TbActivityLog");
                });

            modelBuilder.Entity("Domains.TbApprovedOffice", b =>
                {
                    b.Property<Guid?>("ApprovedOfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ApprovedOfficeLicenseDoc")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ApprovedOfficeLogo")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ApprovedOfficeName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ApprovedOfficeShortDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("EvaluationNoOfStatrs")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("EvaluationNumerical")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApprovedOfficeId");

                    b.ToTable("TbApprovedOffice");
                });

            modelBuilder.Entity("Domains.TbArea", b =>
                {
                    b.Property<Guid?>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<Guid?>("CityId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("AreaId");

                    b.HasIndex("CityId");

                    b.ToTable("TbAreas");
                });

            modelBuilder.Entity("Domains.TbCharge", b =>
                {
                    b.Property<Guid?>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ChargeTypeReciever")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeTypeSender")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ChargeValue")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<Guid?>("ConsultingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("IdReciever")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdSender")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RecieverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ChargeId");

                    b.ToTable("TbCharge");
                });

            modelBuilder.Entity("Domains.TbChat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("ConsultingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RecieverEmail")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RecieverFirstName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RecieverId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RecieverUserType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SenderAudio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SenderFirstName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SenderText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUserType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ChatId");

                    b.ToTable("TbChat");
                });

            modelBuilder.Entity("Domains.TbCity", b =>
                {
                    b.Property<Guid?>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CityId");

                    b.ToTable("TbCities");
                });

            modelBuilder.Entity("Domains.TbComplainsAndSuggestion", b =>
                {
                    b.Property<Guid?>("ComplaintsAndSuggestionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ComplaintsAndSuggestionsText")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Idd")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ComplaintsAndSuggestionsId");

                    b.ToTable("TbComplainsAndSuggestion");
                });

            modelBuilder.Entity("Domains.TbConsultingEstablish", b =>
                {
                    b.Property<Guid?>("ConsultingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CaseShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingDateAndTime")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingPeriod")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingPeriodCost")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingTypeId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingVatvalue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ConsultingVATValue");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("DayOfCancellation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelegationAskLawyerReplyBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelegationPromocodeDiscountValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelegationRejectionCause")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DelegationReplyBack")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DelegationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelegationValueApproved")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DelegationValueSentFromLawyer")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DelegationValueSentFromUser")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<Guid?>("DocumentationOfContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentationOfContractTilte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumnetationRequestShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDelegationAsked")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("MainConsultingId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("MainConsultingName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("MyfatoorahInvoiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfOffers")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentGatePercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentGatePercentDelegation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentGateTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentGateTitleDelegation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentGatesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentGatesIdDelegation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymnetGateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymnetGateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromocodeDiscountValue")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ProposedCustomerPay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestAudio")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RequestDocument")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RequestDocument2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDocument3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDocument4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDocument5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNo")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RequestStatus")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RequestText")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubConsultingId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SubConsultingName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TheConsultingPaidValue")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TheDocumentationPaidValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheTotal")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TheTotalDelegation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeRemainingForConsultingToStart")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UnDefinedSubConsultingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UserFamilyName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UserPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsultingId");

                    b.ToTable("TbConsultingEstablish");
                });

            modelBuilder.Entity("Domains.TbConsultingType", b =>
                {
                    b.Property<Guid?>("ConsultingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ConsultingTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ConsultingTypeId");

                    b.ToTable("TbConsultingType");
                });

            modelBuilder.Entity("Domains.TbDocumentationOfContract", b =>
                {
                    b.Property<Guid?>("DocumentationOfContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("DocumentationOfContractCost")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DocumentationOfContractDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DocumentationOfContractImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DocumentationOfContractTilte")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("DocumentationOfContractId");

                    b.ToTable("TbDocumentationOfContract");
                });

            modelBuilder.Entity("Domains.TbEvaluation", b =>
                {
                    b.Property<Guid?>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ConsultationServiceId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("EvaluaterId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("EvaluaterImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("EvaluationText")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("StartsNo")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ToBeEvaluatedId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ToBeEvaluatedImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("EvaluationId");

                    b.ToTable("TbEvaluation");
                });

            modelBuilder.Entity("Domains.TbEvaluationApprovedOffice", b =>
                {
                    b.Property<Guid?>("EvaluationApprovedOfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ApprovedOfficeId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ApprovedOfficeLogo")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ApprovedOfficeName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("EvaluaterId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("EvaluaterImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("EvaluaterName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("EvaluationApprovedOfficeText")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("StartsNo")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("EvaluationApprovedOfficeId");

                    b.ToTable("TbEvaluationApprovedOffice");
                });

            modelBuilder.Entity("Domains.TbLawyerAppintments", b =>
                {
                    b.Property<Guid?>("LawyerAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<double?>("FromHour")
                        .HasColumnType("float");

                    b.Property<string>("LawyerId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MorEveFrst")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("MorEveScond")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<double?>("ToHour")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("WeekDay")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("LawyerAppointmentId");

                    b.ToTable("TbLawyerAppintments");
                });

            modelBuilder.Entity("Domains.TbLawyerPeriodCostConsult", b =>
                {
                    b.Property<Guid?>("LawyerPeriodCostConsultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ConsultingPeriod")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConsultingPeriodCost")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("LawyerId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("LawyerPeriodCostConsultId");

                    b.ToTable("TbLawyerPeriodCostConsult");
                });

            modelBuilder.Entity("Domains.TbLogHistory", b =>
                {
                    b.Property<Guid?>("LogHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<Guid?>("LoggedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoggedUserName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("LogHistoryId");

                    b.ToTable("TbLogHistory");
                });

            modelBuilder.Entity("Domains.TbMainConsulting", b =>
                {
                    b.Property<Guid?>("MainConsultingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Consulting30MinutesCost")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Consulting60MinutesCost")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Consulting90MinutesCost")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("MainConsultingImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("MainConsultingTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("MainConsultingId");

                    b.ToTable("TbMainConsulting");
                });

            modelBuilder.Entity("Domains.TbNotification", b =>
                {
                    b.Property<Guid?>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ToWhomId")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ToWhomName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("NotificationId");

                    b.ToTable("TbNotification");
                });

            modelBuilder.Entity("Domains.TbOffer", b =>
                {
                    b.Property<Guid?>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("ConsultingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())")
                        .IsFixedLength(true);

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<string>("LawyerEvalNoStarts")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyerShortDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyersEvalNumerical")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LawyersExperinceYears")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Notes")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("OfferEndDate")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("OfferStatus")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2")
                        .IsFixedLength(true);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("OfferId");

                    b.ToTable("TbOffer");
                });

            modelBuilder.Entity("Domains.TbPaymentGates", b =>
                {
                    b.Property<Guid?>("PaymentGatesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ActivationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PaymentGateImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PaymentGateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PaymentGatesId");

                    b.ToTable("TbPaymentGates");
                });

            modelBuilder.Entity("Domains.TbPoliciesAndPrivacy", b =>
                {
                    b.Property<Guid?>("PoliciesAndPrivacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PoliciesAndPrivacyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PoliciesAndPrivacyForWhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PoliciesAndPrivacyTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PoliciesAndPrivacyId");

                    b.ToTable("TbPoliciesAndPrivacy");
                });

            modelBuilder.Entity("Domains.TbPromocode", b =>
                {
                    b.Property<Guid?>("PromocodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PromocodeDiscountPercent")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PromocodeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PromocodeId");

                    b.ToTable("TbPromocode");
                });

            modelBuilder.Entity("Domains.TbRealTimeNotifcation", b =>
                {
                    b.Property<Guid>("RealTimeNotifcationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("NotificationSyntax")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("RealTimeNotifcationId");

                    b.ToTable("TbRealTimeNotifcations");
                });

            modelBuilder.Entity("Domains.TbServices", b =>
                {
                    b.Property<Guid?>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ServiceId");

                    b.ToTable("TbServicess");
                });

            modelBuilder.Entity("Domains.TbSetting", b =>
                {
                    b.Property<Guid?>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AppProfitPercent")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("OffersValidityDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TimeBetweenTwoConsultation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ValueAddedTax")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("SettingId");

                    b.ToTable("TbSetting");
                });

            modelBuilder.Entity("Domains.TbSubMainConsulting", b =>
                {
                    b.Property<Guid?>("SubMainConsultingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<Guid?>("MainConsultingId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MainConsultingTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SubMainConsulting")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("SubMainConsultingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SubMainConsultingImage")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SubMainConsultingTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("SubMainConsultingId");

                    b.ToTable("TbSubMainConsulting");
                });

            modelBuilder.Entity("Domains.TbTermAndCondition", b =>
                {
                    b.Property<Guid?>("TermsAndConditionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TermsAndConditionsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TermsAndConditionsForWhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TermsAndConditionsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("TermsAndConditionsId");

                    b.ToTable("TbTermAndCondition");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domains.TbArea", b =>
                {
                    b.HasOne("Domains.TbCity", "City")
                        .WithMany("TbAreas")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_TbAreas_TbCities")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domains.TbCity", b =>
                {
                    b.Navigation("TbAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
